spring:
  mvc:
    servlet:
      path: /api
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  datasource:
    url: ${db.url:}
    username: ${db.username:}
    password: ${db.password:}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 60000
      maximum-pool-size: 50
logging:
  file:
    max-history: 20
auth:
  salt: msv